from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('chats', views.chat, name='chat'),
    path('log', views.log, name='log'),
    path('add_product', views.add_product, name='add_product'),
    path('category/<int:category_id>/', views.category_products, name='category_products'),
    path('send_message/', views.send_message, name='send_message'),
    path('get_chat_messages/', views.get_chat_messages, name='get_chat_messages'),
    path('chats/<int:chat_id>/', views.view_chat, name='view_chat'),
    path('profile/<str:username>/', views.profile_user, name='profile_user'),
    path('profile_other/<str:username>/', views.view_other_profile, name='view_other_profile'),
    path('account/settings_user/', views.settings_user, name='settings_user'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('update-username/', views.update_username, name='update_username'),
    path('update-password/', views.update_password, name='update_password'),
    path('update_email/', views.update_email, name='update_email'),
    path('update_security/', views.update_security, name='update_security'),
    path('product-not-available/', views.product_not_available, name='product_not_available'),
    path('logout/', views.my_logout_view, name='logout'),
    path('product/<int:product_id>/order_checkout/', views.order_checkout, name='order_checkout'),
    path('autocomplete-address/', views.autocomplete_address, name='autocomplete_address'),
    path('product/<int:product_id>/order_checkout/order_confirmation/<int:reserved_order_id>/', views.order_confirmation, name='order_confirmation'),
    path('finance/', views.finance, name='finance'),
    path('order/<int:order_id>/pay/', views.pay_order, name='pay_order'),
    path('sales_history/', views.sales_history, name='sales_history'),
    path('ship_order/<int:order_id>/', views.ship_order, name='ship_order'),
    path('product_detail_with_chat/<int:product_id>/<int:order_id>/', views.product_detail_with_chat, name='product_detail_with_chat'),
    path('leave_review/', views.leave_review, name='leave_review'),
    path('cancel_order/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path('update-user-status/', views.update_user_status, name='update_user_status'),
    path('search/', views.search_products, name='search_products'),
    path('block_user/', views.block_user, name='block_user'),
    path('report_user/', views.report_user, name='report_user'),
    path('unblock_user/', views.unblock_user, name='unblock_user'),
    path('order/<int:order_id>/confirm/', views.confirm_payment, name='confirm_payment'),
    path('update_avatar/', views.update_avatar, name='update_avatar')
]
