# Generated by Django 5.0.3 on 2024-06-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_product_category_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdelivery',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='pickuppoint',
            name='delivery_method',
        ),
        migrations.RemoveField(
            model_name='productdelivery',
            name='product',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='PickupPoint',
        ),
        migrations.DeleteModel(
            name='ProductDelivery',
        ),
    ]
